// <auto-generated />
namespace tasky.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class taskmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taskmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201307101559160_taskmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
