// <auto-generated />
namespace tasky.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class burndown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(burndown));
        
        string IMigrationMetadata.Id
        {
            get { return "201307221828234_burndown"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
