// <auto-generated />
namespace tasky.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class taskmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taskmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201307101406545_taskmodels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
