// <auto-generated />
namespace tasky.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class logs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logs));
        
        string IMigrationMetadata.Id
        {
            get { return "201307191520184_logs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
